import 'user_model.dart';

class MockUser{
  static final List<User> users = <User>[
    User(
        id: 0,
        firstName: "Cillian",
        lastName: "Murphy",
        phone: "367-987",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSbC7mXcoI7vi3Pm2uC44-oWL3Q2puz0zYhw&s",
        isOnline: true,
        hasStory: true,
        age: 47,
        lastOnline: "Last activity 1 min",
        score: 4.7),
    User(
        id: 1,
        firstName: "Bred",
        lastName: "Pit",
        phone: "287-182",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH4XbmiJTy9VKXScLVNiLaUPUgRbUyzEkd_Q&s",
        isOnline: true,
        hasStory: true,
        age: 61,
        lastOnline: "Last activity 12 min",
        score: 3.9),
    User(
        id: 2,
        firstName: "Christofer",
        lastName: "Nolan",
        phone: "717-091",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrK0sExq-4iN7MD3avyY7oABl-Uc2kKC7dzA&s",
        isOnline: false,
        hasStory: true,
        age: 54,
        lastOnline: "Last activity 23 min",
        score: 4.2),
    User(
        id: 3,
        firstName: "Tom",
        lastName: "Cruise",
        phone: "617-019",
        imageUrl: "https://img.goodfon.ru/wallpaper/big/4/f8/tom-cruise-tom-kruz-aktior-ulybka.webp",
        isOnline: false,
        hasStory: false,
        age: 62,
        lastOnline: "Last activity 43 min",
        score: 4.0),
    User(
        id: 4,
        firstName: "Jackie",
        lastName: "Chan",
        phone: "617-019",
        imageUrl: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-858141682.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        isOnline: true,
        hasStory: true,
        age: 70,
        lastOnline: "Last activity 14 min",
        score: 4.3),
    User(
        id: 5,
        firstName: "Bruce",
        lastName: "Lee",
        phone: "677-019",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/Bruce-Lee-as-Kato-1967-retouched.jpg",
        isOnline: false,
        hasStory: false,
        age: 85,
        lastOnline: "Last activity 58 min",
        score: 3.1),
    User(
        id: 2,
        firstName: "Christofer",
        lastName: "Nolan",
        phone: "717-091",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrK0sExq-4iN7MD3avyY7oABl-Uc2kKC7dzA&s",
        isOnline: false,
        hasStory: true,
        age: 54,
        lastOnline: "Last activity 23 min",
        score: 4.2),
    User(
        id: 3,
        firstName: "Tom",
        lastName: "Cruise",
        phone: "617-019",
        imageUrl: "https://img.goodfon.ru/wallpaper/big/4/f8/tom-cruise-tom-kruz-aktior-ulybka.webp",
        isOnline: false,
        hasStory: false,
        age: 62,
        lastOnline: "Last activity 43 min",
        score: 4.0),
    User(
        id: 4,
        firstName: "Jackie",
        lastName: "Chan",
        phone: "617-019",
        imageUrl: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-858141682.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        isOnline: true,
        hasStory: true,
        age: 70,
        lastOnline: "Last activity 14 min",
        score: 4.3),
    User(
        id: 0,
        firstName: "Cillian",
        lastName: "Murphy",
        phone: "367-987",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSbC7mXcoI7vi3Pm2uC44-oWL3Q2puz0zYhw&s",
        isOnline: true,
        hasStory: true,
        age: 47,
        lastOnline: "Last activity 1 min",
        score: 4.7),
    User(
        id: 1,
        firstName: "Bred",
        lastName: "Pit",
        phone: "287-182",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH4XbmiJTy9VKXScLVNiLaUPUgRbUyzEkd_Q&s",
        isOnline: true,
        hasStory: true,
        age: 61,
        lastOnline: "Last activity 12 min",
        score: 3.9),
    User(
        id: 4,
        firstName: "Jackie",
        lastName: "Chan",
        phone: "617-019",
        imageUrl: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-858141682.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        isOnline: true,
        hasStory: true,
        age: 70,
        lastOnline: "Last activity 14 min",
        score: 4.3),
    User(
        id: 0,
        firstName: "Cillian",
        lastName: "Murphy",
        phone: "367-987",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSbC7mXcoI7vi3Pm2uC44-oWL3Q2puz0zYhw&s",
        isOnline: true,
        hasStory: true,
        age: 47,
        lastOnline: "Last activity 1 min",
        score: 4.7),
    User(
        id: 5,
        firstName: "Bruce",
        lastName: "Lee",
        phone: "677-019",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/Bruce-Lee-as-Kato-1967-retouched.jpg",
        isOnline: false,
        hasStory: false,
        age: 85,
        lastOnline: "Last activity 58 min",
        score: 3.1),
    User(
        id: 2,
        firstName: "Christofer",
        lastName: "Nolan",
        phone: "717-091",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrK0sExq-4iN7MD3avyY7oABl-Uc2kKC7dzA&s",
        isOnline: false,
        hasStory: true,
        age: 54,
        lastOnline: "Last activity 23 min",
        score: 4.2),
    User(
        id: 3,
        firstName: "Tom",
        lastName: "Cruise",
        phone: "617-019",
        imageUrl: "https://img.goodfon.ru/wallpaper/big/4/f8/tom-cruise-tom-kruz-aktior-ulybka.webp",
        isOnline: false,
        hasStory: false,
        age: 62,
        lastOnline: "Last activity 43 min",
        score: 4.0),
    User(
        id: 4,
        firstName: "Jackie",
        lastName: "Chan",
        phone: "617-019",
        imageUrl: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-858141682.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        isOnline: true,
        hasStory: true,
        age: 70,
        lastOnline: "Last activity 14 min",
        score: 4.3),
    User(
        id: 3,
        firstName: "Tom",
        lastName: "Cruise",
        phone: "617-019",
        imageUrl: "https://img.goodfon.ru/wallpaper/big/4/f8/tom-cruise-tom-kruz-aktior-ulybka.webp",
        isOnline: false,
        hasStory: false,
        age: 62,
        lastOnline: "Last activity 43 min",
        score: 4.0),
    User(
        id: 4,
        firstName: "Jackie",
        lastName: "Chan",
        phone: "617-019",
        imageUrl: "https://hips.hearstapps.com/hmg-prod/images/gettyimages-858141682.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        isOnline: true,
        hasStory: true,
        age: 70,
        lastOnline: "Last activity 14 min",
        score: 4.3),
    User(
        id: 5,
        firstName: "Bruce",
        lastName: "Lee",
        phone: "677-019",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/Bruce-Lee-as-Kato-1967-retouched.jpg",
        isOnline: false,
        hasStory: false,
        age: 85,
        lastOnline: "Last activity 58 min",
        score: 3.1),
    User(
        id: 2,
        firstName: "Christofer",
        lastName: "Nolan",
        phone: "717-091",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrK0sExq-4iN7MD3avyY7oABl-Uc2kKC7dzA&s",
        isOnline: false,
        hasStory: true,
        age: 54,
        lastOnline: "Last activity 23 min",
        score: 4.2),
    User(
        id: 3,
        firstName: "Tom",
        lastName: "Cruise",
        phone: "617-019",
        imageUrl: "https://img.goodfon.ru/wallpaper/big/4/f8/tom-cruise-tom-kruz-aktior-ulybka.webp",
        isOnline: false,
        hasStory: false,
        age: 62,
        lastOnline: "Last activity 43 min",
        score: 4.0),
  ];

  static List<User> workList = [];
}